// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCORWLGHaI6pasp8yX_d5i75SbCjr0cZW4',
    appId: '1:752598869710:web:f331b2264a87483f37929f',
    messagingSenderId: '752598869710',
    projectId: 'reddit-2f573',
    authDomain: 'reddit-2f573.firebaseapp.com',
    storageBucket: 'reddit-2f573.appspot.com',
    measurementId: 'G-YSZ8B93PTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb66k0wYr4AmkiplBHL0smIhv9WAqo-sg',
    appId: '1:752598869710:android:281911bae0dff37e37929f',
    messagingSenderId: '752598869710',
    projectId: 'reddit-2f573',
    storageBucket: 'reddit-2f573.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF4heekTgbpmqUfg-QfFsPpM_Vd4h2-tE',
    appId: '1:752598869710:ios:470d389cca69851537929f',
    messagingSenderId: '752598869710',
    projectId: 'reddit-2f573',
    storageBucket: 'reddit-2f573.appspot.com',
    iosClientId: '752598869710-sd99vhbv309pk0i0tlb1mt3c9in6vh09.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF4heekTgbpmqUfg-QfFsPpM_Vd4h2-tE',
    appId: '1:752598869710:ios:4aec1c3974f6dcc337929f',
    messagingSenderId: '752598869710',
    projectId: 'reddit-2f573',
    storageBucket: 'reddit-2f573.appspot.com',
    iosClientId: '752598869710-3vepjnh2m0k1mgvfs9n2pjt82pht3nbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit.RunnerTests',
  );
}
